name: Test Webcam Script with Docker and Unittest

on:
  push:
    branches:
      - master
      - preprod
      - hotfix
      - webcam
  pull_request:
    branches:
      - master
      - preprod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        cd Dev/Camera
        docker build -t webcam-test-image -f Dockerfile .

    - name: Run tests in Docker container
      run: docker run --rm webcam-test-image
